Hc metadata parent
onflow/hybrid-custody pull request #119
Opened 2023-07-07 17:01 UTC by FelipeRibeiroLabs

2023-07-07 18:11 UTC, austinkline requested changes
Two small pieces, looks good otherwise so far!

1. Comment cleanup
2. How should a parent remove a display on a child?

2023-07-07 18:11 UTC, austinkline commented on contracts/HybridCustody.cdc
> +        // field.
This comment isn't really accurate anymore, maybe something like:

```suggestion
        // display metadata for a child account exists on its parent
```

2023-07-07 18:11 UTC, austinkline commented on contracts/HybridCustody.cdc
> +        pub fun setChildAccountDisplay(address: Address, _ d: MetadataViews.Display) {
We either need a way for a display to be removed on this method (let it be an optional display and remove from the dictionary if nil, or we should add a new method

2023-07-07 20:10 UTC, sisyphusSmiling commented
> How should a parent remove a display on a child?

I think setting as `nil` like you mentioned is a lightweight method for deletion, and an upsert if not nil makes sense to me for this use case.

2023-07-08 01:35 UTC, austinkline approved these changes

2023-07-10 15:09 UTC, merged